[build]
	publish = "_site"
	command = "npm run build"

[[redirects]]
from = "/new/"
to = "https://early-ford-v-8-foundation.square.site/product/-25-new-member/264?cp=true&sa=false&sbp=false&q=false&category_id=17"
status = 301
